[package]
name = "swc-plugin-power-assert"
version = "0.7.0"
edition = "2021"
authors = ["Takuto WADA <takuto.wada@gmail.com>"]
include = ["Cargo.toml", "src/**/*.rs"]
license = "MIT"
description = """
SWC plugin for power-assert
"""

[lib]
crate-type = ["cdylib"]
# crate-type = ["cdylib", "rlib"]

# [profile.release]
# lto = true

[dependencies]
rustc-hash = "2"
swc_core = { version = "29.4.*", features = ["ecma_plugin_transform"] }
bytes-str = "0.2.*"

[dev-dependencies]
swc_ecma_transforms_testing = "21.0.*"
swc_ecma_parser = "17.2.*"
testing = "14.0.*"

# dealing with "the trait `Hash` is not implemented for `serde_json::Value`"
serde_json = "1.0.*"

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
